---
# tasks file for jenkins
- debug: msg="Will install Jenkins"

- name: downloading jenkins repo
  get_url: url=http://pkg.jenkins.io/redhat-stable/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo
- name: jenkins repo key
  rpm_key: state=present key=http://pkg.jenkins.io/redhat-stable/jenkins.io.key
- name: install
  yum: name={{ item }} state=latest
  with_items:
    - jenkins
    - git
- name: JENKINS | changing jenkins user group
  user: name=jenkins groups=tomcat
- name: copying config files
  template: src=jenkins dest=/etc/sysconfig/
  notify: restart jenkins
- name: copying files
  copy: src={{ item.src }} dest={{ item.dest }} force={{ item.force| default("yes")}} owner=jenkins group=jenkins
  with_items:
    - {src: "config.xml", dest: "/var/lib/jenkins/"}
    - {src: "hudson.tasks.Maven.xml", dest: "/var/lib/jenkins/"}
    - {src: "plugins", dest: "/var/lib/jenkins", force: "no"}
    - {src: "jobs", dest: "/var/lib/jenkins", force: "no"}
  notify: restart jenkins

- name: start jenkins
  service: name=jenkins state=started
