---
# tasks file for jenkins


    - shell: sudo wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins-ci.org/redhat/jenkins.repo
    - shell: sudo rpm --import https://jenkins-ci.org/redhat/jenkins-ci.org.key

    - name: install jenkins
      yum: name=jenkins state=present

    - name: Copy jenkins conf
      template: src=jenkins dest=/etc/sysconfig/jenkins

    - name: Copy jenkins conf.xml
      template: src=config.xml dest=/var/lib/jenkins/config.xml

    - name: Jobs for Jenkins
      copy: src=jobs dest=/var/lib/jenkins/ force=no

    - name: Plugins for Jenkins
      copy: src=plugins dest=/var/lib/jenkins/ force=no

    - name: Copying Maven config for Jenkins
      copy: src=hudson.tasks.Maven.xml dest=/var/lib/jenkins/ force=no

    - name: Changing Jenkins home directory ownership
      file: path=/var/lib/jenkins owner=jenkins group=jenkins state=directory recurse=yes

    - name: Install git
      yum: name=git state=present

    - name: Edit sudoers
      copy: src=jenkins-user dest=/etc/sudoers.d/ force=no

    - name: Start jenkins
      service: name=jenkins state=running
