---
# tasks file for nginx

    - name: Install nginx
      yum: name=nginx state=latest

    - name: Copy config
      template: src=default.conf dest=/etc/nginx/conf.d/default.conf

    - name: Start nginx
      service: name=nginx state=running


