- name: get nginx
  yum: name=nginx state=latest

- name: copy conf
  copy: src=vhosts.conf dest=/etc/nginx/conf.d/vhosts.conf force=yes
  
- name: copy conf 2
  copy: src=default.conf dest=/etc/nginx/conf.d/default.conf force=yes
  
- name: service nginx
  service: name="nginx" state=restarted enabled=yes