Vagrant.configure(2) do |config|

        config.vm.hostname = "cent6"
		config.vm.network "forwarded_port", guest: 8080, host: 8080
		config.ssh.username = "root"
		config.vm.box = "sbeliakou/centos-6.7-x86_64"
		config.vm.provider :virtualbox do |v|
                v.name = "centos6"
                v.customize ["modifyvm", :id, "--memory", 2048]
		end
        config.vm.provision :ansible_local do |ansible|
					ansible.playbook       = "ansible/provision.yml"
					ansible.verbose        = true
					ansible.install        = true
		end
end
