---
# tasks file for web
- debug: msg="Will install NGINX"
- name: NGINX | Installing NGINX repo rpm
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
- name: Nginx | Nginx install
  yum: name=nginx state=latest
- name: Copy config
  template: src=virtual.conf dest=/etc/nginx/conf.d/virtual.conf
- name: NGINX | Starting nginx
  service: name=nginx state=running

