---
# tasks file for web
- debug: msg="Will install NginX"
- name: NGINX | Installing NGINX repo rpm
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
- name: Nginx | Nginx install
  yum: name=nginx state=latest
- name: changing nginx config
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
- name: NGINX | Starting nginx
  service: name=nginx state=running
