- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    nginx_port: 8080
    tomcat_port: 9090
    jenkins_port: 10100
    java_version: java-1.7.0-openjdk-devel.x86_64

  pre_tasks:
  - debug: msg="Provision started."

  roles:
  - nginx
  - tomcat
  - jenkins

  post_tasks:
  - debug: msg="All tasks were done."
