- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
   nginx_repo: http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
   nginx_port: 8080
   tomcat_port: 9080
   jenkins_prefix: --prefix=/jenkins
   jenkins_port: 8081 

  pre_tasks:
  - debug: msg="Let's do this"

  roles:
  - jenkins
  - tomcat
  - web

  post_tasks:
  - debug: msg="well done" 
