- name: Provision with Ansible
  hosts: all
  become: yes

  vars:
    nginx_port: 8080
    tomcat_port: 8081
    jenkins_port: 8082
    jenkins_plugins: ["git", "maven-plugin", "delivery-pipeline-plugin", "copyartifact"]

  pre_tasks:
  - debug: msg="Let's do this"

  roles:
  - java
  - jenkins
  - tomcat
  - web

  post_tasks:
  - debug: var=services_info.split('\n')
