- name: Check if needed JAVA version installed
  shell: java -version 2>&1 | grep java | awk '{print $2}' | sed 's/\"//g'
  register: jv

- name: Downloading JDK
  get_url:
    url: http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-linux-x64.rpm
    dest: /opt/jdk-7u79-linux-x64.rpm
    headers: "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie"
  when: jv.stdout != "1.7.0_79"

- name: Installing JDK
  yum:  name=/opt/jdk-7u79-linux-x64.rpm state=present
  when: jv.stdout != "1.7.0_79"

- name: Adding java to alternatives
  alternatives: name={{ item }}  link=/usr/bin/java path=/usr/java/jdk1.7.0_79/bin/{{ item }}
  when: jv.stdout != "1.7.0_79"
  with_items: 
  - java
  - javac

- name: Deleting archive in case java is presented on the system
  file: path=/opt/jdk-7u79-linux-x64.rpm state=absent
  when: jv.stdout != "1.7.0_79"